# Generated by Django 5.2 on 2025-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benesseregiornaliero',
            options={'verbose_name_plural': 'Benessere Giornaliero'},
        ),
        migrations.AlterModelOptions(
            name='diarioalimentare',
            options={'verbose_name_plural': 'Diario Alimentare'},
        ),
        migrations.AddField(
            model_name='misurazione',
            name='bmi_descrizione',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='misurazione',
            name='bmi_valore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
