# Generated by Django 5.2 on 2025-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_benesseregiornaliero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allenamento',
            name='esercizio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
