# Generated by Django 5.2 on 2025-05-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_allenamento_esercizio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misurazione',
            old_name='bmi_descrizione',
            new_name='bmi_descr',
        ),
        migrations.AddField(
            model_name='misurazione',
            name='bfm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
